#define MAINPREFIX z
#define PREFIX medbag
#define QPREFIX QUOTE(PREFIX)
#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH
#define VERSION_AR  MAJOR,MINOR,PATCH
#define AUTHOR YonV
#define QAUTHOR QUOTE(AUTHOR)

#define REQUIRED_VERSION 2.00

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(MEDBAG - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(MEDBAG - COMPONENT)
#endif
